# Generated by Django 6.0 on 2026-01-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('ANM', 'Animation'), ('CMD', 'Comedy'), ('CRM', 'Crime'), ('DOC', 'Documentary'), ('DRM', 'Drama'), ('FNT', 'Fantasy'), ('HOR', 'Horror'), ('MSC', 'Musical'), ('MST', 'Mystery'), ('RMC', 'Romance'), ('SFY', 'Science-Fiction'), ('SPT', 'Sports'), ('TRL', 'Thriller'), ('WAR', 'War'), ('WST', 'Western')], max_length=50)),
                ('rating', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG13', 'PG-13'), ('R', 'R'), ('NC17', 'NC-17')], max_length=5)),
                ('description', models.CharField(max_length=500)),
                ('length', models.DurationField()),
                ('image', models.CharField(max_length=250)),
            ],
        ),
    ]
